# This workflow will install Python dependencies and build static call-graph

name: callgraph

on:
  push:
    branches: [ "main" ]
    paths: [ "mol2chemfigPy3/*.py", "docs/*.py" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "mol2chemfigPy3/*.py", "docs/*.py" ]

permissions:
  contents: write
  issues: none

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt update
        python -m pip install git+https://github.com/Technologicat/pyan.git
        sudo apt install graphviz
    - name: Build static call-graph
      run: |
        python docs/build_callgraph.py
    - name: Check for Changes
      id: check_changes
      run: |
        if [[ -n "$(git diff --exit-code)" ]]; then
          echo "Changes detected."
          echo "has_changes=true" >> $GITHUB_OUTPUT
        else
          echo "No changes detected."
          echo "has_changes=false" >> $GITHUB_OUTPUT
        fi
    - name: Push to repository
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git config --global user.signingkey ${{ secrets.NOREPLY_GPG_KEY_ID }}
        git config --global commit.gpgsign true
        git config --global tag.gpgSign true

        # stage any file changes to be committed
        git add .

        # make commit with staged changes
        git commit -m 'Updated call-graph'

        # push the commit back up to source GitHub repository
        git push
